# Generated by Django 4.2.3 on 2023-11-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_free', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Fail',
                'verbose_name_plural': 'Fails',
            },
        ),
    ]
