# Generated by Django 4.2.3 on 2023-12-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fails', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fail',
            name='score',
            field=models.IntegerField(default=60),
            preserve_default=False,
        ),
    ]
