# Generated by Django 4.2.3 on 2023-12-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fails', '0004_fail_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='fail',
            name='semester',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fail',
            name='subject_credit',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
