# Generated by Django 4.2.3 on 2023-11-22 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passport_given_by',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
