# Generated by Django 4.2.3 on 2023-07-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build', models.CharField(choices=[('A_BUILD', 'A_BUILD'), ('B_BUILD', 'B_BUILD'), ('C_BUILD', 'C_BUILD')], default='A_BUILD', max_length=7)),
                ('number', models.IntegerField()),
                ('type_room', models.CharField(choices=[('LECTURE', 'LECTURE'), ('PRACTICE', 'PRACTICE')], default='LECTURE', max_length=8)),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
            },
        ),
    ]
