# Generated by Django 4.2.3 on 2023-08-13 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniverGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level', models.SmallIntegerField(blank=True, default=1, null=True)),
                ('type_education', models.CharField(choices=[('FULL_TIME', 'FULL_TIME'), ('EVENING', 'EVENING'), ('DISTANCE_LEARNING', 'DISTANCE_LEARNING')], default='FULL_TIME', max_length=17)),
                ('language', models.CharField(choices=[('UZ', 'UZ'), ('RU', 'RU'), ('EN', 'EN')], default='UZ', max_length=2)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculties.faculty')),
            ],
            options={
                'verbose_name': 'UniverGroup',
                'verbose_name_plural': 'UniverGroups',
            },
        ),
    ]
