# Generated by Django 4.2.3 on 2023-11-10 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetakeCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_index', models.IntegerField(unique=True)),
                ('case', models.TextField()),
                ('agreement_file', models.FileField(upload_to='files/agreement/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'Retake Case',
                'verbose_name_plural': 'Retake Cases',
            },
        ),
        migrations.CreateModel(
            name='Retake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('UZ', 'UZ'), ('RU', 'RU'), ('EN', 'EN')], default='UZ', max_length=2)),
                ('retake_date', models.DateField(blank=True, null=True)),
                ('retake_time', models.TimeField(blank=True, null=True)),
                ('case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='retake.retakecase')),
                ('retake_room', models.ForeignKey(default='Meet the Dean', on_delete=django.db.models.deletion.SET_DEFAULT, to='rooms.room')),
            ],
            options={
                'verbose_name': 'Retake',
                'verbose_name_plural': 'Retakes',
            },
        ),
    ]
