# Generated by Django 4.2.3 on 2023-11-22 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retake', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retakecase',
            name='agreement_file',
        ),
    ]
