# Generated by Django 4.2.3 on 2023-11-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('exam_type', models.CharField(choices=[('TEST', 'TEST'), ('WRITE', 'WRITE')], max_length=5)),
                ('hide', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
            },
        ),
    ]
