# Generated by Django 4.2.3 on 2023-08-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='hide',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
