# Generated by Django 4.2.3 on 2023-11-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='department',
            field=models.ManyToManyField(related_name='departments', to='departments.department'),
        ),
    ]
